endpoints:
  login: 'https://api.channel4.com/online/v2/auth/token'
  title: 'https://api.channel4.com/online/v1/views/content-hubs/{title}.json'
  license: 'https://c4.eme.lp.aws.redbeemedia.com/wvlicenceproxy-service/widevine/acquire'

keys:
  web:
    key: 'n9cLieYkqwzNCqvi'  # aka bytes1
    iv: 'odzcU3WdUiXLucVd'  # aka bytes2

  android:
    key: 'AYDID8SDFBP4M8DH'
    iv: '1DCD0383DKDFSL82'

client:
  id: '36UUCt98VMQvBAgQ27Au8zGHl31N9LQ1'
  secret: 'JYswyHvGe62VlikW'
  # c4, yv, ios, xbox, ps, wp8, xboxone, roku, freesat, android, samsung, win8, fvc, yvweb, cast, amazonfire,
  # android-mod, fvp, samsung-dash, virginall4, yvdash, samsungorsay, xbox-dash, xboxone-dash, roku-dash,
  # amazonfire-dash, ps-dash, cast-dash, skyoverip
  name: 'android-mod'  # web: c4, android: android-mod

device:
  platform_name: 'android'
  device_type: 'mobile'
  device_name: 'Asus Nexus Player (fugu)'  # 'Sony C6903 (C6903)'
  app_version: 'android_app:9.2.5'
  optimizely_datafile: '2908'
