user_agent: 'AppleTV6,2/11.1'  # AppleTV6,2/11.1 | ATVE/1.1 FireOS/6.2.6.8 build/4A93 maker/Amazon model/FireTVStick4K FW/NS6268/2315

endpoints:
  title: 'https://tv.apple.com/api/uts/v3/{type}/{id}'
  tv_episodes: 'https://tv.apple.com/api/uts/v2/view/show/{id}/episodes'
  manifest: 'https://tv.apple.com/api/uts/v2/view/product/{id}/personalized'
  license: 'https://play.itunes.apple.com/WebObjects/MZPlay.woa/web/video/subscription/license'

device:
  # I have no idea what these values are or what they represent.
  # These might not even be device related.
  utsk: '6e3013c6d6fae3c2::::::e08f7cfb96228836'  # 6e3013c6d6fae3c2::::::e08f7cfb96228836 (?),  6e3013c6d6fae3c2::::::235656c069bb0efb (web)
  caller: 'web' # ?, vz, web
  sf: '143441'  # "storefront", country | 143441: US, 143444: GB
  v: '46'  # "version" | latest: 46
  pfm: 'appletv'  # "platform" | appletv, vz, web
  mfr: 'Apple'  # "manufacturer" | Apple, Amazon
  locale: 'en-US'
  l: 'en'
  ctx_brand: 'tvs.sbd.4000'
  count: '100'
  skip: '0'
