user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'
appversion: '1.2.7.42'

endpoints:
  video: 'https://api.pluto.watchabc.go.com/api/ws/pluto/v1/layout?authlevel=0&brand=011&device=001&type=vod_player&video={id}'
  show: 'https://api.pluto.watchabc.go.com/api/ws/pluto/v1/layout?authlevel=0&brand=011&device=001&type=show&show={id}'
  manifest: 'https://prod.gatekeeper.us-abc.symphony.edgedatg.go.com/vp2/ws-secure/entitlement/2020/playmanifest_secure.json'
  web: 'https://disneynow.com/shows/{name}/season-{season}/episode-{episode}/{id}'
  license: 'https://content.uplynk.com/wv'
